---

- name: copy GitLab ca cert
  copy:
    src: hosts/{{ inventory_hostname_short }}/etc/ssl/gitlab-ext.intra.drop-pay.io.ca.crt
    dest: /etc/ssl/gitlab-ext.intra.drop-pay.io.ca.crt
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644
  tags:
    - conf

- name: copy configuration files
  copy:
    src: hosts/{{ inventory_hostname_short }}{{ item.path }}
    dest: "{{ item.path }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "{{ item.mode }}"
  with_items:
    - { path: /etc/default/jenkins, mode: "0644" }
    - { path: /etc/init.d/jenkins, mode: "0755" }
  notify:
    - reload jenkins
  tags:
    - conf
