---

- name: deploy /etc
  copy:
    src: hosts/{{ inventory_hostname_short }}{{ item.path }}
    dest: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ files }}"
  notify: restart network
  tags:
    - conf

- name: deploy ssh authorized keys
  copy:
    src: hosts/{{ inventory_hostname_short }}/authorized_keys
    dest: /home/{{ user }}/.ssh/authorized_keys
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644
  tags:
    - conf
